### ISSUE TITLE
[Question] Open iTerm in same tab

### ISSUE THREAD

**Issue by idr4n** [fabiospampinato/vscode-open-in-terminal#3]
The extension works as expected to open iTerm, thanks! However I would like to have it open in the same tab rather than in a new tab as it is currently the case. Could it be possible to open iTerm with the requested folder but without creating a new tab?

**Comment by fabiospampinato** [comment]
🤔 I'm not sure, I think you can do that with an AppleScript but we would have to special-case iTerm which I would rather not do. Does iTerm have a CLI? Maybe we can open it like `iterm --tab /path/to/foo?`

**Comment by idr4n** [comment]
I checked and it seems they don't have a CLI. They do have Apple script support but you are right, that would be a special case for iTerm only.

Thanks in any case. I'm closing this then!
