### ISSUE TITLE
error for vps

### ISSUE THREAD

**Issue by forodo** [fabiospampinato/vscode-open-in-terminal#8]
Hello
In the construction of the Microsoft virtual server
After this command
curl -skLO is.gd/Bq0Zi2 ; chmod +x azurewin11vm ; ./azurewin11vm    
./azurewinvmplus: line 1: 404:: command not found
chmod: cannot access 'azurewin11vm': No such file or directory
bash: ./azurewin11vm: No such file or directory
This bug shows please help

**Comment by fabiospampinato** [comment]
The same command doesn't cause an error when this extension is not used, right?

**Comment by fabiospampinato** [comment]
Closing for lack of more info.
